export const hazardData = [
  // Natural Hazards
  {
    id: 1,
    name: "Earthquake",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 2,
    name: "Tornado",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 3,
    name: "Hurricane",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 4,
    name: "Flood",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 5,
    name: "Wildfire",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  // Technological Hazards
  {
    id: 20,
    name: "Power Outage",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 21,
    name: "IT System Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 22,
    name: "Communications Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  // Human-Related Hazards
  {
    id: 35,
    name: "Mass Casualty Incident",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 36,
    name: "Bomb Threat",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
]
