export const hazardData = [
  // Natural Hazards
  {
    id: 1,
    name: "Earthquake",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 2,
    name: "Tornado",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 3,
    name: "Hurricane",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 4,
    name: "Flood",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 5,
    name: "Wildfire",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 6,
    name: "Landslide",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 7,
    name: "Extreme Heat",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 8,
    name: "Extreme Cold",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 9,
    name: "Snowstorm",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 10,
    name: "Ice Storm",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 11,
    name: "Drought",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 12,
    name: "Epidemic",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 13,
    name: "Pandemic",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 14,
    name: "Coastal Erosion",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 15,
    name: "Tsunami",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },

  // Technological Hazards
  {
    id: 20,
    name: "Power Outage",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 21,
    name: "IT System Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 22,
    name: "Communications Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 23,
    name: "Water System Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 24,
    name: "HVAC Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 25,
    name: "Fire Alarm Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 26,
    name: "Medical Gas Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 27,
    name: "Medical Vacuum Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 28,
    name: "Generator Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 29,
    name: "Transportation Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 30,
    name: "Fuel Shortage",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 31,
    name: "Natural Gas Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 32,
    name: "Sewer Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 33,
    name: "Steam Failure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 34,
    name: "Fire",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },

  // Human-Related Hazards
  {
    id: 35,
    name: "Mass Casualty Incident",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 36,
    name: "Bomb Threat",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 37,
    name: "Chemical Spill",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 38,
    name: "Civil Disturbance",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 39,
    name: "Labor Action",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 40,
    name: "Active Shooter",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 41,
    name: "Hostage Situation",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 42,
    name: "VIP Situation",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 43,
    name: "Infant/Child Abduction",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 44,
    name: "Supply Chain Shortage",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 45,
    name: "Medication Shortage",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 46,
    name: "Radiologic Exposure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 47,
    name: "Biological Exposure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 48,
    name: "Chemical Exposure",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
  {
    id: 49,
    name: "Terrorism",
    probability: 0,
    alerts: 0,
    activations: 0,
    humanImpact: 0,
    propertyImpact: 0,
    businessImpact: 0,
    preparedness: 0,
    internalResponse: 0,
    externalResponse: 0,
  },
]
